---
title: "Visualizing fish data"
output: 
  html_document:
    fig.retina: 1
date: "October 2023"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.showtext = TRUE)
```

```{r}
library(PointedSDMs)
library(ggplot2)
library(raster)
library(INLA)
library(dplyr)
library(tidyverse)
library(sf)
library(patchwork)
library(showtext)

showtext_auto()

f1 <- "Open sans"
font_add_google(f1, f1)
```


```{r}
# MAP --------------------------------------------------------------------------
norway <- ggplot2::map_data("world", region = "Norway(?!:Svalbard)")
norway <- setdiff(norway, dplyr::filter(norway, subregion == "Jan Mayen"))
proj <- CRS("+proj=longlat +ellps=WGS84")
norwayfill <- maps::map("world", "norway", fill=TRUE, plot=FALSE, 
                  ylim=c(58,72), xlim=c(4,32))
IDs <- sapply(strsplit(norwayfill$names, ":"), function(x) x[1])
norway.poly <- maptools::map2SpatialPolygons(norwayfill, IDs = IDs, 
                                             proj4string = proj)
```

# Before running model 

```{r}
Data_survey_df <- readRDS("data/survey_clean_new.rds") 
Data_artsobs_df <- readRDS("data/artsobs_clean_new.rds")
```

```{r}
colors_fish <- c("hotpink4", "darkgoldenrod2", "darkgreen", "darkcyan")
```


```{r}
p_artsobs <- ggplot(Data_artsobs_df, aes(x = decimalLongitude, y = decimalLatitude)) +
  geom_polygon(data = norway, aes(long, lat, group = group), 
               color="grey80", fill = "grey95") + 
  geom_point(aes(color = species), size = 0.5, alpha = 0.3) +
  facet_wrap(~species, nrow = 1) +
  scale_color_manual(values = colors_fish) +
  coord_map() +
  ylab("Latitude") +
  labs(tag = "Citizen science data") +
  theme_minimal() +
  theme(text = element_text(family = f1),
        plot.tag = element_text(angle = 90, hjust = 0.5),
        plot.tag.position = c(-0.03, 0.45),
        legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

p_survey <- ggplot(Data_survey_df %>% filter(occurrenceStatus == 1), 
       aes(x = decimalLongitude, y = decimalLatitude)) +
  geom_polygon(data = norway, aes(long, lat, group = group), 
               color="grey80", fill = "grey95") + 
  geom_jitter(aes(color = species), size = 0.5, alpha = 0.3) +#, width = 0.1, height = 0.1) +
  facet_wrap(~species, nrow = 1) +
  scale_color_manual(values = colors_fish) +
  coord_map() +
  xlab("Longitude") +
  ylab("Latitude") +
  labs(tag = "Survey data") +
  theme_minimal() +
  theme(text = element_text(family = f1),
        plot.tag = element_text(angle = 90, hjust = 0.5),
        plot.tag.position = c(-0.03, 0.45),
        legend.position = "none",
        strip.text = element_blank(),
        plot.margin = margin(l = 30))

p_artsobs / p_survey

ggsave("figures/presence_points.pdf", height = 5, width = 8)
```

Where are the observations made in general?

```{r}
p_survey_density <- ggplot(Data_survey_df, 
                           aes(x = decimalLongitude, y = decimalLatitude)) +
  geom_polygon(data = norway, aes(long, lat, group = group), 
               color="grey80", fill = "grey95") + 
  geom_hex() +
  facet_wrap(~species, nrow = 1) +
  scale_fill_gradient(low = "darkcyan", high = "gold") +
  coord_map() +
  ylab("Survey data") +
  theme_minimal() +
  theme(text = element_text(family = f1),
        legend.position = "none",
        axis.title.x = element_blank())

p_artsobs_density <- ggplot(Data_artsobs_df, 
                           aes(x = decimalLongitude, y = decimalLatitude)) +
  geom_polygon(data = norway, aes(long, lat, group = group), 
               color="grey80", fill = "grey95") + 
  geom_hex() +
  facet_wrap(~species, nrow = 1) +
  scale_fill_gradient(low = "darkcyan", high = "gold") +
  coord_map() +
  ylab("Citizen science data") +
  theme_minimal() +
  theme(text = element_text(family = f1),
        legend.position = "none",
        axis.title.x = element_blank(),
        strip.text = element_blank())

p_survey_density / p_artsobs_density

ggsave("figures/density_plots.pdf", height = 5, width = 8)

```

## Plots from the model

```{r}
plot_preferences <- list(scale_fill_distiller(palette = "Spectral"), #, limits = c(-8, 8)),
                         coord_map(),
                         xlab("Longitude"),
                         ylab("Latitude"),
                         theme_minimal(),
                         theme(text = element_text(family = f1))
                         )
```


```{r}
# Plot shared spatial field ----------------------------------------------------
plot_species <- function(predictions, species, plot_preferences){
  p <- ggplot() +
    gg(predictions$speciesPredictions[[species]]) +
    labs(title = species) +
    plot_preferences 
  
  return(p)
}

plot_list <- list()
fishes <- c("Salmo_trutta", "Perca_fluviatilis", 
            "Esox_lucius", "Salvelinus_alpinus")
for(fish in fishes) {
  plot_list[[fish]] <- plot_species(
    predictions = readRDS(paste0("results/sharedfield_", fish, ".rds")),
    species = fish,
    plot_preferences = plot_preferences
  )
}


# Plot biasfield ---------------------------------------------------------------
four_fish_biasfield <- readRDS("results/four_fish_biasfield.rds")

biasplot <- ggplot() +
  gg(four_fish_biasfield$biasFields$four_fish_artsobs) +
  labs(title = "Bias field") +
  plot_preferences 
```

```{r}
library(patchwork)
#purrr::reduce(plot_list, `|`) / (biasplot + plot_spacer() + plot_spacer() + plot_spacer())
#ggsave("figures/fishplot.pdf", width = 12, height = 8)

wrap_plots(plot_list$Salmo_trutta, plot_list$Perca_fluviatilis, plot_list$Esox_lucius, plot_list$Salvelinus_alpinus, biasplot, nrow = 3)

ggsave("figures/fishplot_three_rows.pdf", width = 7, height = 7)
```

